\subsection{Introducción}


\subsection{Análisis exploratorio}

```{r}
kurtosis((scale(resumen_kurtosis$n100k0)))
kurtosis(c(resumen_kurtosis$n100k0))
kurtosis(c(resumen_kurtosis$n100k21.41))
```

```{r}
population.model <- ' f1 =~ x1 + 0.8*x2 + 1.2*x3
                      f2 =~ x4 + 0.5*x5 + 1.5*x6
                      f3 =~ x7 + 0.1*x8 + 0.9*x9

                      f3 ~ 0.5*f1 + 0.6*f2
                    '

# generate data


  
  myData <- simulateData(population.model, sample.nobs=1e5, kurtosis = rep(24, 9))
psych::describe(myData)


mod1 <- ' f1 =~ x1 + x2 + x3
            f2 =~ x4 + x5 + x6
            f3 =~ x7 + x8 + x9

            f3 ~ f1 + f2
          '

fit <- sem(mod1, data = myData)
standardizedSolution(fit)
```

```{r}
  myData <- simulateData(population.model, sample.nobs=1e5, kurtosis = rep(3, 9))
psych::describe(myData)


mod1 <- ' f1 =~ x1 + x2 + x3
            f2 =~ x4 + x5 + x6
            f3 =~ x7 + x8 + x9

            f3 ~ f1 + f2
          '

fit <- sem(mod1, data = myData)
standardizedSolution(fit)
```

```{r}
  myData <- simulateData(population.model, sample.nobs=1e5, kurtosis  = rep(12, 9))
psych::describe(myData)

mod1 <- ' f1 =~ x1 + x2 + x3
            f2 =~ x4 + x5 + x6
            f3 =~ x7 + x8 + x9

            f3 ~ f1 + f2'

fit <- sem(mod1, data = myData)
standardizedSolution(fit)
```

```{r}
modelo <- ' CA =~ 0.88*x1 + 0.77*x2 + 0.73*x3
            PHC =~ 0.85*x4 + 0.80*x5 + 0.82*x6
            VE =~ 0.62*x7 + 0.74*x8 + 0.72*x9

            VE ~ -0.01*CA + 0.41*PHC
          '

library(semPlot)
semPaths(semPlotModel_lavaanModel(modelo))

library(mnormt)
set.seed(123)
# Define sample size
N <- 10000
# Define the Fixed Parameters
alpha <- c(0, 0, 0)  # latent means
Phi <- matrix(c(1, 0, -0.01, 
                0, 1, 0.41,
                -0.01, 0.41, 1.1682), nrow = 3)  # latent variances/covariances
Lambda <- cbind(c(0.88, 0.77, 0.73, 0, 0, 0, 0, 0, 0), 
                c(0, 0, 0, 0.85, 0.80, 0.82, 0, 0, 0),
                c(0, 0, 0, 0, 0, 0, 0.62, 0.74, 0.72))  # factor loadings
Theta <- diag(1, nrow = 9)
# Generate latent factor scores
eta <- rmnorm(N, mean = alpha, varcov = Phi)
#eta[,3] <- -0.01 * eta[,1] + 0.41 * eta[,2] + rnorm(N)
# Generate residuals:
e <- rmnorm(N, varcov = Theta)
# Compute outcome scores: y_i = t(Lambda %*% eta_i) + e
y <- tcrossprod(eta, Lambda) + e
# Make it a data frame
colnames(y) <- paste0("x", 1:9)
df <- as.data.frame(y)


library(lavaan)

mod1 <- ' CA =~ x1 + x2 + x3
            PHC =~ x4 + x5 + x6
            VE =~ x7 + x8 + x9

            VE ~ CA + PHC
          '

fit <- sem(mod1, data = df, std.lv = F, orthogonal = T)
summary(fit, standardize = T)


set.seed(123)
df1 <- simulateData(modelo, std.lv = F, sample.nobs = 1e5)
fit <- sem(mod1, data = df1, std.lv = F, orthogonal = T)
summary(fit, standardize = T)

```

